knp_gaufrette:
    stream_wrapper:
        protocol: pedstorage
    adapters:
        local_adapter:
            local:
                directory:     "%kernel.project_dir%/public/%env(STORAGE_LOCAL_DIRECTORY)%"
        amazon_s3_adapter:
            aws_s3:
                service_id:    "ped_storage.aws_s3.client"
                bucket_name:   "%env(STORAGE_AMAZON_S3_BUCKET_NAME)%"
                options:
                    create:    true
                    directory: "%env(STORAGE_AMAZON_S3_DIRECTORY)%"
    filesystems:
        local_fs:
            adapter: local_adapter
            alias:   local_fs
        amazon_fs:
            adapter: amazon_s3_adapter
            alias:   amazon_fs
