knp_gaufrette:
    stream_wrapper:
        protocol: pedstorage
    adapters:
        local_adapter:
            local:
                directory:     "%ped_storage.local.directory%"
        amazon_s3_adapter:
            aws_s3:
                service_id:    "ped_storage.aws_s3.client"
                bucket_name:   "%ped_storage.amazon_s3.bucket_name%"
                options:
                    create:    true
                    directory: "%ped_storage.amazon_s3.directory%"
    filesystems:
        local_fs:
            adapter: local_adapter
            alias:   local_fs
        amazon_fs:
            adapter: amazon_s3_adapter
            alias:   amazon_fs
