ped_database_swift_mailer:
    max_retries: "%env(int:SMD_MAX_RETRIES)%"
    delete_sent_messages: "%env(bool:SMD_DELETE_SENT_MESSAGES)%"
    entity_manager: "%env(string:SMD_ENTITY_MANAGER)%"
    auto_flush: "%env(bool:SMD_AUTO_FLUSH)%"
